### ISSUE TITLE
About compiling the AP_OpticalFlow_test.ino 

### ISSUE THREAD

**Issue by olivercxu** [Lauszus/ADNS3080#1]
When compiling the AP_OpticalFlow_test.ino ,(in Arduino 1.6.9 Win64 ver) ,I got the mistake:            exit status 1
use of enum 'Rotation' without previous declaration
I don't why....Can you fix it ?

**Comment by Lauszus** [comment]
Just delete the directory "AP_OpticalFlow_test" and you should be able to compile the code.
